swagger: "2.0"
info:
  title: pom
  description: pom's web interface
  version: ""
host: localhost:8421
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /state:
    get:
      tags:
      - get
      summary: state get
      operationId: get#state
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
